export const SBU_MAJORS = [
  "Accounting",
  "Africana Studies",
  "Anthropology",
  "Applied Mathematics & Statistics",
  "Art History & Criticism",
  "Art, Studio",
  "Asian & Asian American Studies",
  "Astronomy/Planetary Sciences",
  "Atmospheric and Oceanic Sciences",
  "Biochemistry",
  "Biology",
  "Biomedical Engineering",
  "Business Management",
  "Chemical & Molecular Engineering",
  "Chemistry",
  "Civil Engineering",
  "Climate Science",
  "Clinical Laboratory Sciences",
  "Coastal Environmental Studies",
  "Communication",
  "Computer Engineering",
  "Computer Science",
  "Creative Writing",
  "Data Science",
  "Earth & Space Sciences",
  "Economics",
  "Education",
  "Electrical Engineering",
  "Engineering Chemistry",
  "Engineering Science",
  "English",
  "Environmental Design, Policy & Planning",
  "Environmental Studies",
  "French Language and Literature",
  "Geology",
  "Globalization Studies & International Relations",
  "Health Science",
  "History",
  "Human Evolutionary Biology",
  "Information Systems",
  "Italian Studies",
  "Journalism",
  "Linguistics",
  "Marine Sciences",
  "Marine Vertebrate Biology",
  "Mass Communication",
  "Mathematics",
  "Mechanical Engineering",
  "Media/Art/Culture",
  "Multidisciplinary Studies",
  "Music",
  "Nursing",
  "Philosophy",
  "Physics",
  "Political Science",
  "Psychology",
  "Respiratory Care",
  "Rhetoric and Writing",
  "Social Work",
  "Sociology",
  "Spanish Language and Literature",
  "Sustainability Studies",
  "Technological Systems Management",
  "Women's and Gender Studies",
]

export const SBU_MINORS = [
  "Africana Studies",
  "Anthropology",
  "Applied Mathematics & Statistics",
  "Art History & Criticism",
  "Art, Studio",
  "Asian & Asian American Studies",
  "Astronomy",
  "Biology",
  "Biomedical Engineering",
  "Business Management",
  "Chemistry",
  "Cinema and Cultural Studies",
  "Communication",
  "Computer Science",
  "Creative Writing",
  "Dance",
  "Data Science",
  "Economics",
  "Education",
  "Electrical Engineering",
  "English",
  "Environmental Studies",
  "European Studies",
  "French",
  "Geology",
  "German",
  "Health & Wellness",
  "History",
  "Information Systems",
  "Italian",
  "Japanese Studies",
  "Journalism",
  "Korean Studies",
  "Linguistics",
  "Marine Sciences",
  "Mathematics",
  "Mechanical Engineering",
  "Music",
  "Philosophy",
  "Physics",
  "Political Science",
  "Psychology",
  "Sociology",
  "Spanish",
  "Sustainability Studies",
  "Theatre Arts",
  "Women's and Gender Studies",
]

export const SBU_COURSE_PREFIXES: Record<string, string> = {
  "AAS": "Asian & Asian American Studies",
  "ACC": "Accounting",
  "ADV": "Advanced Graduate Courses",
  "AFH": "Africana Studies",
  "AFS": "Air Force Studies",
  "AMS": "Applied Mathematics & Statistics",
  "ANT": "Anthropology",
  "ARB": "Arabic",
  "ARH": "Art History",
  "ARS": "Art Studio",
  "ASC": "Arts & Sciences",
  "AST": "Astronomy",
  "ATM": "Atmospheric Sciences",
  "BCP": "Biochemistry & Cell Biology",
  "BIO": "Biology",
  "BME": "Biomedical Engineering",
  "BUS": "Business Management",
  "CAR": "Career Development",
  "CCS": "Cinema & Cultural Studies",
  "CDS": "Computational Data Science",
  "CEF": "Civil Engineering Fundamentals",
  "CHE": "Chemistry",
  "CHI": "Chinese",
  "CIS": "Cinema Studies",
  "CIV": "Civil Engineering",
  "CLL": "Comparative Literature",
  "CLS": "Clinical Laboratory Sciences",
  "CLT": "Cultural Studies",
  "CME": "Chemical & Molecular Engineering",
  "COM": "Communication",
  "CSE": "Computer Science",
  "CWL": "Creative Writing & Literature",
  "DAN": "Dance",
  "EAS": "East Asian Studies",
  "EBH": "Ecology & Behavioral Biology",
  "ECO": "Economics",
  "EDP": "Educational Policy",
  "EEL": "Electrical Engineering Lab",
  "EEO": "Electrical Engineering Online",
  "EGL": "English",
  "ENS": "Engineering Science",
  "ENV": "Environmental Studies",
  "ESE": "Electrical & Computer Engineering",
  "ESG": "Environmental Science Gateway",
  "ESM": "Engineering Science & Mechanics",
  "EST": "Technological Systems Management",
  "EUR": "European Studies",
  "FLA": "Foreign Languages",
  "FLM": "Film Studies",
  "FRN": "French",
  "GEO": "Geosciences",
  "GER": "German",
  "GLI": "Global Studies",
  "GRK": "Greek",
  "GSS": "Graduate Social Sciences",
  "HAD": "Health Administration",
  "HAN": "Honors Arts & Sciences",
  "HIN": "Hindi",
  "HIS": "History",
  "HON": "Honors College",
  "HWC": "Health & Wellness",
  "ISE": "Information Systems Engineering",
  "ITL": "Italian",
  "JPN": "Japanese",
  "JRN": "Journalism",
  "KOR": "Korean",
  "LAC": "Latin American & Caribbean Studies",
  "LAN": "Languages",
  "LAT": "Latin",
  "LIN": "Linguistics",
  "MAE": "Marine & Atmospheric Engineering",
  "MAP": "Marine & Atmospheric Policy",
  "MAR": "Marine Sciences",
  "MAT": "Mathematics",
  "MDA": "Media Arts",
  "MEC": "Mechanical Engineering",
  "MSL": "Military Science & Leadership",
  "MUS": "Music",
  "MVL": "Marine Vertebrate Lab",
  "NUR": "Nursing",
  "OAE": "Oceanic & Atmospheric Engineering",
  "PER": "Performance",
  "PHI": "Philosophy",
  "PHY": "Physics",
  "POL": "Political Science",
  "POR": "Portuguese",
  "PSY": "Psychology",
  "RLS": "Religious Studies",
  "RUS": "Russian",
  "SBU": "Stony Brook University",
  "SOC": "Sociology",
  "SPN": "Spanish",
  "SSE": "Social Studies Education",
  "SUS": "Sustainability Studies",
  "SWA": "Swahili",
  "THR": "Theatre Arts",
  "TRK": "Turkish",
  "UKR": "Ukrainian",
  "WRT": "Writing & Rhetoric",
  "WST": "Women's & Gender Studies",
}

export function isValidCoursePrefix(prefix: string): boolean {
  return prefix.toUpperCase() in SBU_COURSE_PREFIXES
}

// Returns matching prefixes with full names for the dropdown
export function getMatchingPrefixes(query: string): { code: string; name: string }[] {
  const q = query.toUpperCase().trim()
  if (q.length < 1) return []

  return Object.entries(SBU_COURSE_PREFIXES)
    .filter(([code, name]) =>
      code.startsWith(q) || name.toUpperCase().includes(q)
    )
    .map(([code, name]) => ({ code, name }))
    .slice(0, 8)
}
